#!/bin/sh
# Copyright 2022 GlitchyByte
# SPDX-License-Identifier: MIT-0

# Install OpenJDK 18 on macOS AArch64.

jdkUrl="https://download.java.net/java/GA/jdk18.0.1.1/65ae32619e2f40f3a9af3af1851d6e19/2/GPL/openjdk-18.0.1.1_macos-aarch64_bin.tar.gz"
javaDest="${HOME}/Library/Java/JavaVirtualMachines"
tempDir=$(mktemp -d)
trap "rm -drf ${tempDir}" 0 2 3 15

# Colors.
c_reset=$(tput sgr0)
c_bold=$(tput bold)
# c_black=$(tput setaf 0)
# c_red=$(tput setaf 1)
c_green=$(tput setaf 2)
c_yellow=$(tput setaf 3)
# c_blue=$(tput setaf 4)
# c_magenta=$(tput setaf 5)
# c_cyan=$(tput setaf 6)
c_white=$(tput setaf 7)
c_command="${c_bold}${c_yellow}"
c_command_var="${c_yellow}"
c_message="${c_bold}${c_white}"
c_message_quote="${c_green}"

# Create Java directory in Library.
echo "${c_command}mkdir -p${c_reset} ${c_command_var}${javaDest}${c_reset}"
mkdir -p ${javaDest}

# Download and untar.
echo "${c_command}curl -s${c_reset} ${c_command_var}${jdkUrl}${c_reset} ${c_command}| tar -xC${c_reset} ${c_command_var}${tempDir}${c_reset}"
curl -s ${jdkUrl} | tar -xC ${tempDir}

# Move Java to Library.
echo "${c_command}mv${c_reset} ${c_command_var}${tempDir}/* ${javaDest}/${c_reset}"
mv ${tempDir}/* ${javaDest}/

echo "${c_message}Make sure your ~/.zshenv contains:${c_reset}"
echo "${c_message_quote}export JAVA_HOME=\$(/usr/libexec/java_home)${c_reset}"
