#!/bin/sh
# Copyright 2022 GlitchyByte
# SPDX-License-Identifier: MIT-0

# Install OpenJDK 19 on macOS x64.

jdkUrl="https://download.java.net/java/GA/jdk19.0.1/afdd2e245b014143b62ccb916125e3ce/10/GPL/openjdk-19.0.1_macos-x64_bin.tar.gz"
jdkDestDir="${HOME}/Library/Java/JavaVirtualMachines"
envScript="${HOME}/.zshenv"
javaHomeLine="export JAVA_HOME=\$(/usr/libexec/java_home)"
tempDir=$(mktemp -d)
trap "rm -drf ${tempDir}" 0 2 3 15

# Colors.
c_reset=$(tput sgr0)
c_bold=$(tput bold)
c_red=$(tput setaf 1)
c_yellow=$(tput setaf 3)
c_white=$(tput setaf 7)
c_command="${c_bold}${c_yellow}"
c_command_var="${c_yellow}"
c_message="${c_bold}${c_white}"
c_error="${c_bold}${c_red}"

# Create Java directory in Library.
echo "${c_command}mkdir -p${c_reset} ${c_command_var}${jdkDestDir}${c_reset}"
mkdir -p ${jdkDestDir}

# Download and untar.
echo "${c_command}curl -s${c_reset} ${c_command_var}${jdkUrl}${c_reset} ${c_command}| tar -xC${c_reset} ${c_command_var}${tempDir}${c_reset}"
curl -s ${jdkUrl} | tar -xC ${tempDir}

# Move JDK to Library.
echo "${c_command}mv${c_reset} ${c_command_var}${tempDir}/* ${jdkDestDir}/${c_reset}"
mv ${tempDir}/* ${jdkDestDir}/

# Add JAVA_HOME.
if test ! -f "${envScript}"; then
    touch "${envScript}"
fi
grepResult=$(grep -qF "${javaHomeLine}" "${envScript}" ; echo $?)
if test "${grepResult}" -ge 2; then
    echo "${c_error}Error adding JAVA_HOME.${c_reset}"
    exit 1
fi
if test "${grepResult}" -eq 0; then
    # Already there!
    exit 0
fi
# Not found. Let's add it.
echo "${javaHomeLine}" >> ${envScript}
echo >> ${envScript}
echo "${c_message}Make sure to close and reopen this terminal.${c_reset}"
